import React from 'react';

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-black text-white py-32 px-6">
      <div className="max-w-4xl mx-auto prose prose-invert prose-p:text-white/70 prose-a:text-purple-400">
        <h1 className="text-4xl font-medium mb-8">Marginly Terms of Service</h1>
        <p className="text-sm font-semibold tracking-wider text-white/40 uppercase mb-12">Effective Date: August 29, 2026</p>
        
        <p>
          Welcome to Marginly. These Terms of Service ("Terms") constitute a legally binding agreement between you (whether personally or on behalf of an entity) and Marginly Inc. ("Marginly," "we," "us," or "our"), concerning your access to and use of the Marginly platform, website, and related services (collectively, the "Services"). By accessing the Services, you agree that you have read, understood, and agreed to be bound by all of these Terms.
        </p>

        <h2 className="text-2xl font-medium mt-12 mb-4">1. Account Registration and Security</h2>
        <p>To use the Services, you must register for an account. You agree to:</p>
        <ul className="list-disc pl-6 space-y-2 text-white/70">
          <li>Provide accurate, current, and complete information during the registration process.</li>
          <li>Maintain and promptly update your account information to keep it accurate, current, and complete.</li>
          <li>Maintain the security and confidentiality of your login credentials and API keys.</li>
          <li>Accept full responsibility for all activities that occur under your account.</li>
        </ul>
        <p className="mt-4">Marginly utilizes Google OAuth and Supabase authentication to ensure secure access. We reserve the right to suspend or terminate your account if any information provided proves to be inaccurate, not current, or incomplete.</p>

        <h2 className="text-2xl font-medium mt-12 mb-4">2. "Bring Your Own Key" (BYOK) Artificial Intelligence</h2>
        <p>
          Marginly provides functionality that allows you to connect third-party Artificial Intelligence services (such as OpenAI or Anthropic) using your own API keys. You acknowledge and agree that:
        </p>
        <ul className="list-disc pl-6 space-y-2 text-white/70">
          <li>You are solely responsible for any costs, fees, or overages incurred on your third-party AI provider accounts as a result of using the Marginly Services.</li>
          <li>Marginly bears zero liability for the output generated by third-party AI models. AI-generated scope definitions, quotes, and summaries should be manually reviewed for accuracy before being sent to your clients.</li>
          <li>You will not use the AI integration to generate illegal, defamatory, or highly restricted content (e.g., protected health information under HIPAA) unless explicitly authorized.</li>
        </ul>

        <h2 className="text-2xl font-medium mt-12 mb-4">3. Intellectual Property Rights</h2>
        <p>
          Unless otherwise indicated, the Services are our proprietary property and all source code, databases, functionality, software, website designs, audio, video, text, photographs, and graphics on the Services (collectively, the "Content") and the trademarks, service marks, and logos contained therein are owned or controlled by us, and are protected by copyright and trademark laws.
        </p>
        <p>
          <strong>Your Data:</strong> You retain complete ownership of all client data, project scopes, and quotes you input into Marginly. By using the Services, you grant us a limited, worldwide, non-exclusive, royalty-free license strictly to host, store, and process your data solely for the purpose of operating the Services for you.
        </p>

        <h2 className="text-2xl font-medium mt-12 mb-4 text-red-400">4. Disclaimer of Warranties</h2>
        <p className="font-bold text-white uppercase tracking-wide mb-2 text-sm">Please read carefully:</p>
        <p>
          THE SERVICES ARE PROVIDED ON AN "AS-IS" AND "AS-AVAILABLE" BASIS. YOU AGREE THAT YOUR USE OF THE SERVICES WILL BE AT YOUR SOLE RISK. TO THE FULLEST EXTENT PERMITTED BY LAW, MARGINLY DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, IN CONNECTION WITH THE SERVICES AND YOUR USE THEREOF, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. MARGINLY MAKES NO WARRANTIES OR REPRESENTATIONS ABOUT THE ACCURACY OR COMPLETENESS OF THE SERVICES' CONTENT OR THE CONTENT OF ANY WEBSITES LINKED TO THE SERVICES.
        </p>

        <h2 className="text-2xl font-medium mt-12 mb-4 text-red-400">5. Limitation of Liability</h2>
        <p>
          IN NO EVENT WILL MARGINLY, OUR DIRECTORS, EMPLOYEES, OR AGENTS BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY DIRECT, INDIRECT, CONSEQUENTIAL, EXEMPLARY, INCIDENTAL, SPECIAL, OR PUNITIVE DAMAGES, INCLUDING LOST PROFIT, LOST REVENUE, LOSS OF DATA, OR OTHER DAMAGES ARISING FROM YOUR USE OF THE SERVICES, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. NOTWITHSTANDING ANYTHING TO THE CONTRARY CONTAINED HEREIN, OUR LIABILITY TO YOU FOR ANY CAUSE WHATSOEVER AND REGARDLESS OF THE FORM OF THE ACTION, WILL AT ALL TIMES BE LIMITED TO THE AMOUNT PAID, IF ANY, BY YOU TO US DURING THE SIX (6) MONTH PERIOD PRIOR TO ANY CAUSE OF ACTION ARISING.
        </p>

        <h2 className="text-2xl font-medium mt-12 mb-4 text-red-400">6. Indemnification</h2>
        <p>
          You agree to defend, indemnify, and hold us harmless, including our subsidiaries, affiliates, and all of our respective officers, agents, partners, and employees, from and against any loss, damage, liability, claim, or demand, including reasonable attorneys' fees and expenses, made by any third party due to or arising out of: (1) your use of the Services; (2) breach of these Terms; (3) any breach of your representations and warranties set forth in these Terms; (4) your violation of the rights of a third party, including but not limited to intellectual property rights.
        </p>

        <h2 className="text-2xl font-medium mt-12 mb-4">7. Termination</h2>
        <p>
          We reserve the right, in our sole discretion and without notice or liability, to deny access to and use of the Services to any person for any reason or for no reason, including without limitation for breach of any representation, warranty, or covenant contained in these Terms. You may terminate your account at any time by using the "Delete Account" function in your dashboard.
        </p>

        <h2 className="text-2xl font-medium mt-12 mb-4">8. Governing Law</h2>
        <p>
          These Terms and your use of the Services are governed by and construed in accordance with the laws of the State of Delaware, applicable to agreements made and to be entirely performed within the State of Delaware, without regard to its conflict of law principles.
        </p>

        <h2 className="text-2xl font-medium mt-12 mb-4">9. Contact Us</h2>
        <p>
          In order to resolve a complaint regarding the Services or to receive further information regarding use of the Services, please contact us at:
          <br /><br />
          <strong>Marginly Inc.</strong><br />
          Email: legal@marginly.com
        </p>
      </div>
    </div>
  );
}
